const data = {
  products: [
    {
      _id: "1",
      name: "Nike AirMax",
      category: "Shoes",
      image: "/images/p-2.jpg",
      price: 220,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Nike",
      category: "Shoes",
      image: "/images/p-3.jpg",
      price: 220,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Nike AirMax2",
      category: "Shoes",
      image: "/images/p-4.jpg",
      price: 220,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "NewBalance",
      category: "Shoes",
      image: "/images/p-5.jpg",
      price: 220,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Nike AirJordan",
      category: "Shoes",
      image: "/images/p-6.jpg",
      price: 220,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Nike AirMax",
      category: "Shoes",
      image: "/images/p-7.jpg",
      price: 220,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
